### PR TITLE
packaging: add xenial

### PR DESCRIPTION
**Pull request by marksvc**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/icu/20)

### CODE REVIEW

**Review by marksvc — COMMENTED** [review]
I don't seem to have an approve option, but I approve.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/icu/20#-:-MyD6tT_8KD-vRt9Dqf2:bq0e7p5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

___
*[.github/workflows/fw_icu4c_ci.yml, line 158 at r2](https://reviewable.io/reviews/sillsdev/icu/20#-MyD4IO23DDIyJA4OCSA:-MyD4IO23DDIyJA4OCSB:b-jdkrl8) ([raw file](https://github.com/sillsdev/icu/blob/77b16fd476ead5aaf95fdee3e9a4c1a40d33e4d5/.github/workflows/fw_icu4c_ci.yml#L158)):*
> ```YAML
>           perl -pi -e 's/focal hirsute/xenial focal hirsute/' /home/runner/work/icu/ci-builder-scripts/bash/common.sh
>           perl -pi -e 's/apt-transport-https/apt-transport-https ca-certificates/' /home/runner/work/icu/ci-builder-scripts/bash/setup.sh
>           perl -pi -e 's/TRACE sudo sbuild-update --update --dist-upgrade --upgrade \$D-\$A/TRACE sudo sbuild-apt \$D-\$A apt-get install apt-transport-https ca-certificates && TRACE sudo sbuild-update --update --dist-upgrade --upgrade \$D-\$A/' /home/runner/work/icu/ci-builder-scripts/bash/setup.sh
> ```

Good. I was thinking we needed to modify the first part of the `if lsb_release == xenial`, but that's for if the _host OS_ is xenial, isn't it. Good job getting this to work. I had a look at the package-build log and see it installing apt-transport-https into the xenial chroot.



_Code quote:_
```YAML
apt-get install apt-transport-https
```

**Comment by marksvc** [comment]
Okay we want to include the .ddeb (debugging symbols) files as well. I made a change for that.

**Comment by marksvc** [comment]
Another part of the PR informs me that I can't approve because I'm the author, so you may need to specify an approval, if we see that the build still works after the latest change.

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/icu/20)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @marksvc)

___
*[.github/workflows/fw_icu4c_ci.yml, line 158 at r2](https://reviewable.io/reviews/sillsdev/icu/20#-MyD4IO23DDIyJA4OCSA:-MyDgGpy3TMxWyZvr1ZN:b-4yb3qe) ([raw file](https://github.com/sillsdev/icu/blob/77b16fd476ead5aaf95fdee3e9a4c1a40d33e4d5/.github/workflows/fw_icu4c_ci.yml#L158)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Good. I was thinking we needed to modify the first part of the `if lsb_release == xenial`, but that's for if the _host OS_ is xenial, isn't it. Good job getting this to work. I had a look at the package-build log and see it installing apt-transport-https into the xenial chroot.
</blockquote></details>

@marksvc  
Do we need the change to common.sh? There is a gerrit change to ci-builder-scripts which removes our need for the other 2 substitutions.

**Comment by marksvc** [comment]
___
*[.github/workflows/fw_icu4c_ci.yml, line 158 at r2](https://reviewable.io/reviews/sillsdev/icu/20#-MyD4IO23DDIyJA4OCSA:-MyEHmjX74H7eU2QvTql:b-kdft9c) ([raw file](https://github.com/sillsdev/icu/blob/77b16fd476ead5aaf95fdee3e9a4c1a40d33e4d5/.github/workflows/fw_icu4c_ci.yml#L158)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

@marksvc  
Do we need the change to common.sh? There is a gerrit change to ci-builder-scripts which removes our need for the other 2 substitutions.
</blockquote></details>

We seemed to at the time. If the build works without it, we can remove it.

**Review by jasonleenaylor — APPROVED** [review]

**Pull request merged**
